import { randomUUID } from "crypto";
import mysql, { type Pool } from "mysql2/promise";
import { MemberAuthError, type PublicMember } from "./memberAuth.js";
import { assertMarketplaceRegistrationAccess } from "./marketplaceAccess.js";

export type ExchangeStatus = "active" | "reserved" | "completed" | "cancelled";
export type ExchangeOfferStatus = "pending" | "accepted" | "rejected" | "cancelled" | "completed";
export type ExchangeMonster = { id: string; name: string; attribute: string | null; type: string | null; level: string | null };
export type ExchangeWant = { monster: ExchangeMonster; quantity: number };
export type ExchangeListing = { id: string; ownerId: string; ownerNickname: string; ownerGameNickname: string; offered: ExchangeWant; wants: ExchangeWant[]; note: string | null; status: ExchangeStatus; reservedByOfferId: string | null; createdAt: string; updatedAt: string };
export type ExchangeOffer = { id: string; exchangeListingId: string; ownerId: string; proposerId: string; proposerNickname: string; proposerGameNickname: string; offered: ExchangeWant; message: string | null; status: ExchangeOfferStatus; respondedAt: string | null; createdAt: string; updatedAt: string; listing?: ExchangeListing };
type Row = Record<string, string | number | Date | null>;
type Db = Pick<Pool, "query" | "execute">;
let pool: Pool | undefined;
function db(): Db { if (pool) return pool; if (!process.env.DATABASE_URL) throw new MemberAuthError("SETUP_ERROR", "거래소 데이터베이스가 설정되지 않았습니다."); pool = mysql.createPool(process.env.DATABASE_URL); return pool; }
function rows(result: unknown): Row[] { return Array.isArray(result) && Array.isArray(result[0]) ? result[0] as Row[] : []; }
function affected(result: unknown) { return Array.isArray(result) && result[0] && typeof result[0] === "object" ? Number((result[0] as { affectedRows?: unknown }).affectedRows || 0) : 0; }
function time(value: unknown) { return value instanceof Date ? value.toISOString() : value ? String(value) : new Date(0).toISOString(); }
function qty(value: unknown, label: string) { const parsed = Number(value); if (!Number.isInteger(parsed) || parsed < 1 || parsed > 9999) throw new MemberAuthError("INVALID_INPUT", `${label}은 1~9,999 사이의 정수로 입력해 주세요.`); return parsed; }
function message(value: unknown) { if (value === undefined || value === null) return null; if (typeof value !== "string" || value.trim().length > 300) throw new MemberAuthError("INVALID_INPUT", "메모는 300자 이하로 입력해 주세요."); return value.trim() || null; }
function monster(value: unknown, label: string): ExchangeMonster { const item = value as Partial<ExchangeMonster>; if (!item?.id || !item?.name) throw new MemberAuthError("INVALID_INPUT", `${label} 헨치를 선택해 주세요.`); return { id: String(item.id), name: String(item.name), attribute: item.attribute ? String(item.attribute) : null, type: item.type ? String(item.type) : null, level: item.level ? String(item.level) : null }; }
function listingFrom(row: Row, wants: ExchangeWant[]): ExchangeListing { return { id: String(row.id), ownerId: String(row.ownerId), ownerNickname: String(row.ownerNickname), ownerGameNickname: String(row.ownerGameNickname), offered: { monster: { id: String(row.offeredMonsterId), name: String(row.offeredMonsterName), attribute: row.offeredMonsterAttribute ? String(row.offeredMonsterAttribute) : null, type: row.offeredMonsterType ? String(row.offeredMonsterType) : null, level: row.offeredMonsterLevel ? String(row.offeredMonsterLevel) : null }, quantity: Number(row.offeredQuantity) }, wants, note: row.note ? String(row.note) : null, status: row.status as ExchangeStatus, reservedByOfferId: row.reservedByOfferId ? String(row.reservedByOfferId) : null, createdAt: time(row.createdAt), updatedAt: time(row.updatedAt) }; }
const listingColumns = "id, owner_id AS ownerId, owner_nickname AS ownerNickname, owner_game_nickname AS ownerGameNickname, offered_monster_id AS offeredMonsterId, offered_monster_name AS offeredMonsterName, offered_monster_attribute AS offeredMonsterAttribute, offered_monster_type AS offeredMonsterType, offered_monster_level AS offeredMonsterLevel, offered_quantity AS offeredQuantity, note, status, reserved_by_offer_id AS reservedByOfferId, created_at AS createdAt, updated_at AS updatedAt";
async function wantsFor(ids: string[]) { if (!ids.length) return new Map<string, ExchangeWant[]>(); const result = await db().query(`SELECT exchange_listing_id AS listingId, monster_id AS monsterId, monster_name AS monsterName, monster_attribute AS monsterAttribute, monster_type AS monsterType, monster_level AS monsterLevel, quantity FROM marketplace_exchange_wants WHERE exchange_listing_id IN (${ids.map(() => "?").join(",")})`, ids); const grouped = new Map<string, ExchangeWant[]>(); rows(result).forEach((row) => { const id = String(row.listingId); const values = grouped.get(id) || []; values.push({ monster: { id: String(row.monsterId), name: String(row.monsterName), attribute: row.monsterAttribute ? String(row.monsterAttribute) : null, type: row.monsterType ? String(row.monsterType) : null, level: row.monsterLevel ? String(row.monsterLevel) : null }, quantity: Number(row.quantity) }); grouped.set(id, values); }); return grouped; }
function offerFrom(row: Row): ExchangeOffer { return { id: String(row.id), exchangeListingId: String(row.exchangeListingId), ownerId: String(row.ownerId), proposerId: String(row.proposerId), proposerNickname: String(row.proposerNickname), proposerGameNickname: String(row.proposerGameNickname), offered: { monster: { id: String(row.offeredMonsterId), name: String(row.offeredMonsterName), attribute: row.offeredMonsterAttribute ? String(row.offeredMonsterAttribute) : null, type: row.offeredMonsterType ? String(row.offeredMonsterType) : null, level: row.offeredMonsterLevel ? String(row.offeredMonsterLevel) : null }, quantity: Number(row.offeredQuantity) }, message: row.message ? String(row.message) : null, status: row.status as ExchangeOfferStatus, respondedAt: row.respondedAt ? time(row.respondedAt) : null, createdAt: time(row.createdAt), updatedAt: time(row.updatedAt) }; }
const offerColumns = "id, exchange_listing_id AS exchangeListingId, owner_id AS ownerId, proposer_id AS proposerId, proposer_nickname AS proposerNickname, proposer_game_nickname AS proposerGameNickname, offered_monster_id AS offeredMonsterId, offered_monster_name AS offeredMonsterName, offered_monster_attribute AS offeredMonsterAttribute, offered_monster_type AS offeredMonsterType, offered_monster_level AS offeredMonsterLevel, offered_quantity AS offeredQuantity, message, status, responded_at AS respondedAt, created_at AS createdAt, updated_at AS updatedAt";
export async function syncExchangeMonsterSnapshot(monster: ExchangeMonster): Promise<void> {
  const values = [monster.name, monster.attribute, monster.type, monster.level, monster.id];
  await Promise.all([
    db().execute("UPDATE marketplace_exchange_listings SET offered_monster_name=?, offered_monster_attribute=?, offered_monster_type=?, offered_monster_level=?, updated_at=updated_at WHERE offered_monster_id=?", values),
    db().execute("UPDATE marketplace_exchange_wants SET monster_name=?, monster_attribute=?, monster_type=?, monster_level=? WHERE monster_id=?", values),
    db().execute("UPDATE marketplace_exchange_offers SET offered_monster_name=?, offered_monster_attribute=?, offered_monster_type=?, offered_monster_level=?, updated_at=updated_at WHERE offered_monster_id=?", values),
  ]);
}

export async function listExchangeListings(query = "") { const keyword = query.trim(); const result = await db().query(`SELECT ${listingColumns} FROM marketplace_exchange_listings WHERE status = 'active' ${keyword ? "AND (offered_monster_name LIKE ? OR note LIKE ?)" : ""} ORDER BY created_at DESC LIMIT 100`, keyword ? [`%${keyword}%`, `%${keyword}%`] : []); const source = rows(result); const wants = await wantsFor(source.map((row) => String(row.id))); return source.map((row) => listingFrom(row, wants.get(String(row.id)) || [])); }
export async function getExchangeListing(id: string) { const result = await db().query(`SELECT ${listingColumns} FROM marketplace_exchange_listings WHERE id = ? LIMIT 1`, [id]); const row = rows(result)[0]; if (!row) return null; const wants = await wantsFor([id]); return listingFrom(row, wants.get(id) || []); }
export async function getMyExchangeMarketplace(memberId: string) {
  const [listingResult, receivedResult, sentResult] = await Promise.all([
    db().query(`SELECT ${listingColumns} FROM marketplace_exchange_listings WHERE owner_id = ? ORDER BY created_at DESC LIMIT 100`, [memberId]),
    db().query(`SELECT ${offerColumns} FROM marketplace_exchange_offers WHERE owner_id = ? ORDER BY created_at DESC LIMIT 100`, [memberId]),
    db().query(`SELECT ${offerColumns} FROM marketplace_exchange_offers WHERE proposer_id = ? ORDER BY created_at DESC LIMIT 100`, [memberId]),
  ]);
  const listingRows = rows(listingResult);
  const wants = await wantsFor(listingRows.map((row) => String(row.id)));
  return { listings: listingRows.map((row) => listingFrom(row, wants.get(String(row.id)) || [])), received: rows(receivedResult).map(offerFrom), sent: rows(sentResult).map(offerFrom) };
}
export async function createExchangeListing(member: PublicMember, input: { offered: unknown; offeredQuantity: unknown; wants: unknown; note?: unknown }) { await assertMarketplaceRegistrationAccess(member, "exchange"); const offered = monster(input.offered, "내가 줄"); const offeredQuantity = qty(input.offeredQuantity, "교환 수량"); if (!Array.isArray(input.wants) || input.wants.length < 1 || input.wants.length > 5) throw new MemberAuthError("INVALID_INPUT", "원하는 헨치는 1~5종 선택해 주세요."); const wants = input.wants.map((item) => { const itemValue = item as { monster?: unknown; quantity?: unknown }; return { monster: monster(itemValue.monster, "원하는"), quantity: qty(itemValue.quantity, "요청 수량") }; }); const id = randomUUID(); await db().execute(`INSERT INTO marketplace_exchange_listings (id,owner_id,owner_nickname,owner_game_nickname,offered_monster_id,offered_monster_name,offered_monster_attribute,offered_monster_type,offered_monster_level,offered_quantity,note) VALUES (?,?,?,?,?,?,?,?,?,?,?)`, [id, member.id, member.nickname, member.gameNickname, offered.id, offered.name, offered.attribute, offered.type, offered.level, offeredQuantity, message(input.note)]); for (const want of wants) await db().execute("INSERT INTO marketplace_exchange_wants (id,exchange_listing_id,monster_id,monster_name,monster_attribute,monster_type,monster_level,quantity) VALUES (?,?,?,?,?,?,?,?)", [randomUUID(), id, want.monster.id, want.monster.name, want.monster.attribute, want.monster.type, want.monster.level, want.quantity]); const listing = await getExchangeListing(id); if (!listing) throw new MemberAuthError("SETUP_ERROR", "교환글을 확인하지 못했습니다."); return listing; }
export async function createExchangeOffer(member: PublicMember, listingId: string, input: { offered: unknown; quantity: unknown; message?: unknown }) { const listing = await getExchangeListing(listingId); if (!listing || listing.status !== "active") throw new MemberAuthError("INVALID_INPUT", "현재 교환 제안을 받을 수 없는 글입니다."); if (listing.ownerId === member.id) throw new MemberAuthError("FORBIDDEN", "본인의 교환글에는 제안할 수 없습니다."); const offered = monster(input.offered, "제안할"); const offeredQuantity = qty(input.quantity, "제안 수량"); const id = randomUUID(); await db().execute("INSERT INTO marketplace_exchange_offers (id,exchange_listing_id,owner_id,proposer_id,proposer_nickname,proposer_game_nickname,offered_monster_id,offered_monster_name,offered_monster_attribute,offered_monster_type,offered_monster_level,offered_quantity,message) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)", [id, listingId, listing.ownerId, member.id, member.nickname, member.gameNickname, offered.id, offered.name, offered.attribute, offered.type, offered.level, offeredQuantity, message(input.message)]); return { id, ownerId: listing.ownerId, proposerGameNickname: member.gameNickname, offeredMonsterName: offered.name, offeredQuantity }; }
export async function cancelExchangeListing(ownerId: string, listingId: string) { const result = await db().execute("UPDATE marketplace_exchange_listings SET status='cancelled' WHERE id=? AND owner_id=? AND status='active'", [listingId, ownerId]); if (!affected(result)) throw new MemberAuthError("INVALID_INPUT", "교환 중인 내 글만 취소할 수 있습니다."); return { id: listingId, status: "cancelled" as const }; }
export async function respondExchangeOffer(ownerId: string, offerId: string, action: "accept" | "reject" | "complete" | "cancel") { const result = await db().query("SELECT exchange_listing_id AS listingId, owner_id AS ownerId, proposer_id AS proposerId, status FROM marketplace_exchange_offers WHERE id = ? LIMIT 1", [offerId]); const offer = rows(result)[0]; if (!offer) throw new MemberAuthError("INVALID_INPUT", "교환 제안을 찾을 수 없습니다."); const isOwner = String(offer.ownerId) === ownerId; const isProposer = String(offer.proposerId) === ownerId; if ((action === "accept" || action === "reject" || action === "complete") && !isOwner) throw new MemberAuthError("FORBIDDEN", "교환글 작성자만 처리할 수 있습니다."); if (action === "cancel" && !isProposer) throw new MemberAuthError("FORBIDDEN", "제안한 회원만 취소할 수 있습니다."); const current = String(offer.status); if (action === "accept" && current === "pending") { if (!affected(await db().execute("UPDATE marketplace_exchange_listings SET status='reserved', reserved_by_offer_id=? WHERE id=? AND owner_id=? AND status='active'", [offerId, offer.listingId, ownerId]))) throw new MemberAuthError("INVALID_INPUT", "교환글이 이미 처리되었습니다."); await db().execute("UPDATE marketplace_exchange_offers SET status='accepted', responded_at=NOW() WHERE id=?", [offerId]); await db().execute("UPDATE marketplace_exchange_offers SET status='rejected', responded_at=NOW() WHERE exchange_listing_id=? AND id<>? AND status='pending'", [offer.listingId, offerId]); } else if (action === "reject" && current === "pending") await db().execute("UPDATE marketplace_exchange_offers SET status='rejected', responded_at=NOW() WHERE id=?", [offerId]); else if (action === "cancel" && current === "pending") await db().execute("UPDATE marketplace_exchange_offers SET status='cancelled', responded_at=NOW() WHERE id=?", [offerId]); else if (action === "complete" && current === "accepted") { await db().execute("UPDATE marketplace_exchange_listings SET status='completed' WHERE id=? AND owner_id=? AND reserved_by_offer_id=?", [offer.listingId, ownerId, offerId]); await db().execute("UPDATE marketplace_exchange_offers SET status='completed' WHERE id=?", [offerId]); } else throw new MemberAuthError("INVALID_INPUT", "처리할 수 없는 교환 제안 상태입니다."); return { id: offerId, action }; }
