import { useEffect, useMemo, useState } from "react";
import { ArrowLeftRight, Loader2, Plus, X } from "lucide-react";
import { toast } from "sonner";
import type { Monster } from "@/types/monster";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { MarketplaceMonsterImage } from "@/components/MarketplaceMarketInfo";
import { useMembership } from "@/contexts/MembershipContext";

type Exchange = { id: string; ownerId: string; ownerNickname: string; ownerGameNickname: string; offered: { monster: { id: string; name: string; attribute: string | null; type: string | null; level: string | null }; quantity: number }; wants: { monster: { id: string; name: string; attribute: string | null; type: string | null; level: string | null }; quantity: number }[]; note: string | null };
const request = async (path: string, init?: RequestInit) => { const res = await fetch(path, { headers: { "Content-Type": "application/json", ...(init?.headers || {}) }, ...init }); const body = await res.json(); if (!res.ok) throw new Error(body.message || "교환 처리에 실패했습니다."); return body; };

export function MarketplaceExchangeBoard({ mode, monsters, onChanged }: { mode: "list" | "register"; monsters: Monster[]; onChanged: () => void }) {
  const { member } = useMembership();
  const [exchanges, setExchanges] = useState<Exchange[]>([]); const [query, setQuery] = useState(""); const [offered, setOffered] = useState<Monster | null>(null); const [offeredQuantity, setOfferedQuantity] = useState("1"); const [wantQuery, setWantQuery] = useState(""); const [wants, setWants] = useState<{ monster: Monster; quantity: string }[]>([]); const [note, setNote] = useState(""); const [proposal, setProposal] = useState<Record<string, { monster: Monster | null; quantity: string; message: string }>>({}); const [busy, setBusy] = useState(false);
  const match = (text: string) => monsters.filter((monster) => text.trim() && monster.name.includes(text.trim())).slice(0, 6);
  const refresh = async () => { try { const data = await request(`/api/marketplace/exchanges?query=${encodeURIComponent(query)}`); setExchanges(data.exchanges || []); } catch (error) { toast.error(error instanceof Error ? error.message : "교환글을 불러오지 못했습니다."); } };
  useEffect(() => { if (mode === "list") void refresh(); }, [mode]);
  const register = async (event: React.FormEvent) => { event.preventDefault(); if (!offered || !wants.length) return toast.error("내가 줄 헨치와 원하는 헨치를 선택해 주세요."); setBusy(true); try { await request("/api/marketplace/exchanges", { method: "POST", body: JSON.stringify({ offeredMonsterId: offered.id, offeredQuantity: Number(offeredQuantity), wants: wants.map((want) => ({ monsterId: want.monster.id, quantity: Number(want.quantity) })), note }) }); toast.success("교환글을 등록했습니다."); setOffered(null); setWants([]); setNote(""); onChanged(); } catch (error) { toast.error(error instanceof Error ? error.message : "교환글 등록에 실패했습니다."); } finally { setBusy(false); } };
  const propose = async (exchangeId: string) => { const value = proposal[exchangeId]; if (!value?.monster) return toast.error("교환 제안할 헨치를 선택해 주세요."); setBusy(true); try { await request(`/api/marketplace/exchanges/${exchangeId}/offers`, { method: "POST", body: JSON.stringify({ offeredMonsterId: value.monster.id, quantity: Number(value.quantity || 1), message: value.message }) }); toast.success("교환 제안을 보냈습니다."); } catch (error) { toast.error(error instanceof Error ? error.message : "교환 제안에 실패했습니다."); } finally { setBusy(false); } };
  const cancel = async (exchangeId: string) => { setBusy(true); try { await request(`/api/marketplace/exchanges/${exchangeId}/cancel`, { method: "PATCH" }); toast.success("교환글을 취소했습니다."); await refresh(); onChanged(); } catch (error) { toast.error(error instanceof Error ? error.message : "교환글 취소에 실패했습니다."); } finally { setBusy(false); } };
  if (mode === "register") return <form onSubmit={register} className="space-y-5 rounded-2xl border border-cyan-400/20 bg-slate-950/70 p-5"><h2 className="text-lg font-black text-cyan-100">교환 등록</h2><p className="text-sm text-slate-400">자사 가격 없이, 내가 줄 헨치와 원하는 헨치 목록을 등록합니다.</p><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="내가 줄 헨치 검색" />{match(query).map((monster) => <button key={monster.id} type="button" onClick={() => { setOffered(monster); setQuery(""); }} className="mr-2 rounded bg-slate-800 px-3 py-2 text-sm text-slate-200">{monster.name}</button>)}{offered && <p className="text-cyan-200">내가 줄 헨치: {offered.name} <Input className="ml-2 inline-flex h-8 w-20" value={offeredQuantity} onChange={(e) => setOfferedQuantity(e.target.value)} /></p>}<Input value={wantQuery} onChange={(e) => setWantQuery(e.target.value)} placeholder="원하는 헨치 추가 검색" />{match(wantQuery).map((monster) => <button key={monster.id} type="button" onClick={() => { if (!wants.some((want) => want.monster.id === monster.id) && wants.length < 5) setWants([...wants, { monster, quantity: "1" }]); setWantQuery(""); }} className="mr-2 rounded bg-violet-950 px-3 py-2 text-sm text-violet-200">+ {monster.name}</button>)}<div className="space-y-2">{wants.map((want) => <div key={want.monster.id} className="flex items-center gap-2 rounded bg-slate-900 p-2 text-sm"><span className="flex-1">원하는 헨치: {want.monster.name}</span><Input className="h-8 w-20" value={want.quantity} onChange={(e) => setWants(wants.map((item) => item.monster.id === want.monster.id ? { ...item, quantity: e.target.value } : item))} /><Button type="button" size="icon" variant="ghost" onClick={() => setWants(wants.filter((item) => item.monster.id !== want.monster.id))}><X className="h-4 w-4" /></Button></div>)}</div><Textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="교환 메모 (선택)" /><Button disabled={busy} className="w-full">{busy ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plus className="mr-2 h-4 w-4" />}교환글 등록</Button></form>;
  return <div className="space-y-4"><div className="flex gap-2"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="교환 헨치 검색" /><Button type="button" onClick={() => void refresh()}>검색</Button></div>{exchanges.length === 0 ? <p className="rounded-xl border border-dashed border-slate-700 p-10 text-center text-slate-500">등록된 교환글이 없습니다.</p> : exchanges.map((exchange) => { const current = proposal[exchange.id] || { monster: null, quantity: "1", message: "" }; const isMine = exchange.ownerId === member?.id; return <article key={exchange.id} className="rounded-2xl border border-violet-400/20 bg-slate-950/70 p-4"><div className="flex gap-3"><MarketplaceMonsterImage monster={exchange.offered.monster} monsters={monsters} /><div><p className="font-bold text-cyan-100">{exchange.ownerNickname} · {exchange.ownerGameNickname}</p><p className="text-sm text-slate-300">내가 줄 헨치: <b>{exchange.offered.monster.name} × {exchange.offered.quantity}</b></p><p className="mt-1 text-sm text-violet-200">원하는 헨치: {exchange.wants.map((want) => `${want.monster.name} × ${want.quantity}`).join(", ")}</p>{exchange.note && <p className="mt-2 text-xs text-slate-500">{exchange.note}</p>}</div></div>{isMine ? <Button className="mt-4" variant="outline" disabled={busy} onClick={() => void cancel(exchange.id)}>교환글 취소</Button> : <div className="mt-4 border-t border-slate-800 pt-3"><Input value={current.monster?.name || ""} onChange={(e) => { const found = monsters.find((monster) => monster.name === e.target.value); setProposal({ ...proposal, [exchange.id]: { ...current, monster: found || null } }); }} placeholder="제안할 헨치 이름을 정확히 입력" /><div className="mt-2 flex gap-2"><Input className="w-20" value={current.quantity} onChange={(e) => setProposal({ ...proposal, [exchange.id]: { ...current, quantity: e.target.value } })} /><Input className="flex-1" value={current.message} onChange={(e) => setProposal({ ...proposal, [exchange.id]: { ...current, message: e.target.value } })} placeholder="제안 메모" /><Button disabled={busy} onClick={() => void propose(exchange.id)}><ArrowLeftRight className="mr-2 h-4 w-4" />교환 제안</Button></div></div>}</article>; })}</div>;
}
